name: "Build main (OpenWatcom v2, Linux)"
on:
  push:
    branches: [ "main" ]
jobs:
  build-watcom:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Build with JWasm and OpenWatcom
      run: |
        wmake -h
    - name: Generate floppy image
      run: |
        cd image
        sh mkimage.sh
        cd ..
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: |
          dist/*
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: 1.44M floppy image
        path: |
          image/edrdos.img
