name: "Build main (OpenWatcom v2, Linux)"
on:
  push:
    branches: [ "main" ]
jobs:
  build-watcom:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Build with JWasm and OpenWatcom
      run: |
        cd ltools/unix
        make
        cd ../../drbio
        wmake -h
        cd ../drdos
        wmake -h
        cd ../command
        wmake -h
        cd ..
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          **/drbio.sys
          **/drdos.sys
          **/command.com
  
