name: "Build (Linux, OpenWatcom v2)"
on:
  push:
    branches: [ "main" ]
jobs:
  build-watcom:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Make build tools
      run: |
        cd ltools/unix
        make
        cd ../..
    - name: Build dual-file binaries
      run: |
        ./build.sh
    - name: Generate dual-file floppy image
      run: |
        cd image
        sh mkimage.sh
        cd ..
    - name: Upload dual-file binaries
      uses: actions/upload-artifact@v4
      with:
        name: EDR-DOS binaries (DRBIO.SYS, DRDOS.SYS flavor)
        path: |
          bin/*
    - name: Upload dual-file image
      uses: actions/upload-artifact@v4
      with:
        name: EDR-DOS 1.44M image (DRBIO.SYS, DRDOS.SYS flavor)
        path: |
          image/edrdos.img
    - name: Build single-file binaries
      run: |
        ./build.sh singlefile
    - name: Generate single-file floppy image
      run: |
        cd image
        sh mkimage.sh singlefile
        cd ..
    - name: Upload single-file binaries
      uses: actions/upload-artifact@v4
      with:
        name: EDR-DOS binaries (KERNEL.SYS flavor)
        path: |
          bin/*
    - name: Upload dual-file image
      uses: actions/upload-artifact@v4
      with:
        name: EDR-DOS 1.44M image (KERNEL.SYS flavor)
        path: |
          image/edrdos.img
    - name: Generate SvarDOS package
      run: |
        ./mkpkg.sh
    - name: Upload SvarDOS package
      uses: actions/upload-artifact@v4
      with:
        name: SvarDOS package
        path: |
          kernel.svp



